filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/*.log
  encoding: utf-8
  multiline.pattern: '^[[:space:]]'
  multiline.negate: false
  multiline.match: after

processors:
- add_cloud_metadata:

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]

setup.kibana:
  host: "http://kibana:5601"
  protocol: "http"
  ssl.enabled: false
